http_path = "/" 
css_dir = "assets/css" 
sass_dir = "assets/scss" 
images_dir = "assets/img"
javascripts_dir = "assets/js" 
output_style = :compressed 
relative_assets = true 
line_comments = false
# generated_images_path = "/images"
# # http_images_dir = "img"
